services:

  database:
    image: "bitnami/postgresql:latest"
    ports:
      - '5432:5432'
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: local_user
      POSTGRES_DB: local_db
      POSTGRES_PASSWORD: local_password